x-common:
  &common
  restart: no

services:
  nginx:
    <<: *common
    ports:
      - 80:80
  web:
    <<: *common
    volumes:
      - ./data:/app/data
    ports:
      - 8000:8000
  worker:
    <<: *common
    volumes:
      - ./data:/app/data
  scheduler:
    <<: *common
  redis:
    <<: *common
    ports:
      - 6379:6379
