services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    logging:
      driver: "local"
    restart: always
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 443:443
    logging:
      driver: "local"
    volumes:
      - /opt/picstylist/etc/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: always
