services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    logging:
      driver: 'local'
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 443:443
    logging:
      driver: 'local'
    depends_on:
      - web
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
