services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    logging:
      driver: local
    restart: always
    healthcheck:
      test: curl -f -sS -m 10 http://localhost:8000/ >/dev/null || exit 1
    deploy:
      resources:
        limits:
          memory: 512M
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 443:443
    logging:
      driver: local
    volumes:
      - ./conf/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: always
    healthcheck:
      test: curl -f -sS -m 10 --cert /etc/nginx/ssl/internal.pem --key /etc/nginx/ssl/internal.key --cacert /etc/nginx/ssl/server.pem --connect-to www.picstylist.com:443:localhost https://www.picstylist.com/static/favicon.png >/dev/null || exit 1
    deploy:
      resources:
        limits:
          memory: 256M
