services:
  nginx:
    ports:
      - 80:80
    restart: no
  web:
    volumes:
      - ./data:/app/data
    ports:
      - 8000:8000
    restart: no
  worker:
    volumes:
      - ./data:/app/data
    restart: no
  scheduler:
    restart: no
  redis:
    ports:
      - 6379:6379
    restart: no
