#cloud-config
# ubuntu 22.04 on digitalocean

fs_setup:
  - label: swap
    device: /swapfile
    filesystem: swap

mounts:
  - ['/swapfile', 'none', 'swap', 'sw', '0', '0']


bootcmd:
  - sysctl -w vm.swappiness=10 vm.vfs_cache_pressure=50 vm.overcommit_memory=1


users:
  - name: victor
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD: /opt/picstylist/bin/deploy'
    ssh_import_id:
      - gh:vsemionov


write_files:
  - path: /root/post-receive
    permissions: '0755'
    content: |
      #!/bin/sh
      
      set -e
      
      APP_NAME="picstylist"
      MAIN_BRANCH="main"
      export GIT_WORK_TREE="/opt/$APP_NAME"
      
      while read oldrev newrev refname
      do
          branch=$(git rev-parse --symbolic --abbrev-ref "$refname")
          if [ "$branch" = "$MAIN_BRANCH" ]
          then
              git checkout -f "$MAIN_BRANCH"
              if [ -n "$(git status --porcelain)" ]
              then
                  echo "Work tree at $GIT_WORK_TREE is dirty."
                  exit 1
              fi
              if [ -f "$GIT_WORK_TREE"/.env ];
              then
                  sudo "$GIT_WORK_TREE"/bin/deploy
              else
                  echo "Warning: Configuration not found, skipping deploy."
              fi
          fi
      done
  - path: /root/post-receive-config
    permissions: '0755'
    content: |
      #!/bin/sh
      
      set -e
      
      APP_NAME="picstylist"
      MAIN_BRANCH="main"
      export APP_TREE="/opt/$APP_NAME"
      
      while read oldrev newrev refname
      do
          branch=$(git rev-parse --symbolic --abbrev-ref "$refname")
          if [ "$branch" = "$MAIN_BRANCH" ]
          then
              old_umask=$(umask)
              umask 0077
              git archive "$MAIN_BRANCH" | tar -x --exclude .gitignore -C "$APP_TREE"
              umask $old_umask
          fi
          if [ -f "$APP_TREE"/app.py ];
          then
              sudo "$APP_TREE"/bin/deploy
          else
              echo "Warning: Application not found, skipping deploy."
          fi
      done


runcmd:
  - rm /root/.ssh/authorized_keys

  - dd if=/dev/zero of=/swapfile bs=1M count=2048
  - chmod '600' /swapfile
  - mkswap /swapfile
  - swapon /swapfile

  - snap refresh

  - chown victor:victor /root/post-receive
  - sudo -u victor mkdir ~victor/picstylist
  - sudo -u victor git init --bare -b main ~victor/picstylist.git
  - mv /root/post-receive ~victor/picstylist.git/hooks/
  - mv ~victor/picstylist ~victor/picstylist.git /opt/

  - chown victor:victor /root/post-receive-config
  - sudo -u victor git init --bare -b main ~victor/picstylist-config.git
  - chmod '700' ~victor/picstylist-config.git
  - mv /root/post-receive-config ~victor/picstylist-config.git/hooks/post-receive
  - mv ~victor/picstylist-config.git /opt/

packages:
  - net-tools
  - docker.io
  - docker-buildx
  - docker-compose-v2

package_update: true
package_upgrade: true
package_reboot_if_required: true
