#!/bin/sh

set -e

REG_USER=victor

cat >/etc/ssh/sshd_config.d/101-custom.conf <<EOF
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
UsePAM no
X11Forwarding no
EOF
chmod 600 /etc/ssh/sshd_config.d/101-custom.conf

# https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-22-04
fallocate -l 2G /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo '/swapfile none swap sw 0 0' >>/etc/fstab
echo 'vm.swappiness=10' >>/etc/sysctl.conf
echo 'vm.vfs_cache_pressure=50' >>/etc/sysctl.conf

adduser $REG_USER
usermod -aG sudo $REG_USER

mkdir ~$REG_USER/.ssh
chmod 700 ~$REG_USER/.ssh
mv ~/.ssh/authorized_keys ~$REG_USER/.ssh/
chown -R $REG_USER:$REG_USER ~$REG_USER/.ssh

apt-get update
apt-get upgrade -y
snap refresh
apt-get dist-upgrade -y

sync
echo "Rebooting in 15s"
sleep 15
reboot
