#!/bin/sh

set -e

APP_NAME="picstylist"

ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ""
echo "Public key:"
cat ~/.ssh/id_ed25519.pub
echo "Copy the public key to GitHub (as a deploy key) and press Enter when done."
read

temp_dir=$(mktemp -d)
cd "$temp_dir"
mkdir $APP_NAME
git clone --bare git@github.com:vsemionov/$APP_NAME.git
sudo mv $APP_NAME $APP_NAME.git /opt/
rmdir "$temp_dir"

cd /opt/$APP_NAME.git/
git --work-tree=/opt/$APP_NAME checkout
cp /opt/$APP_NAME/conf/git/* hooks/

echo "Done."
echo "Please add any necessary files under /opt/$APP_NAME now."
echo "When done, run: sudo bin/deploy"
