#cloud-config
fs_setup:
  - label: swap
    device: /swapfile
    filesystem: swap
mounts:
  - ['/swapfile', 'none', 'swap', 'sw', '0', '0']
bootcmd:
  - sysctl -w vm.swappiness=10 vm.vfs_cache_pressure=50 vm.overcommit_memory=1
disable_root: true
disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding
users:
  - name: victor
    shell: /bin/bash
    groups: sudo
    sudo: ALL=(ALL) 'NOPASSWD:' /opt/picstylist/bin/deploy
    ssh_import_id:
      - gh:vsemionov
runcmd:
  - dd if=/dev/zero of=/swapfile bs=1M count=2048
  - chmod '600' /swapfile
  - mkswap /swapfile
  - swapon /swapfile
packages:
  - net-tools
  - docker.io
  - docker-buildx
  - docker-compose-v2
