#!/bin/bash

set -e

export GIT_WORK_TREE="/opt/picstylist"
MAIN_BRANCH="main"

while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref "$refname")
    if [ "$branch" == "$MAIN_BRANCH" ]
    then
        git checkout -f "$MAIN_BRANCH"
        if [ -n "$(git status --porcelain)" ]
        then
            echo "Work tree at $GIT_WORK_TREE is dirty."
            exit 1
        fi
        cd "$WORK_TREE"
        sudo bin/deploy
    fi
done
